### PR TITLE
Add timeout to childprocess

### PR DESCRIPTION
**Pull request by prefork**
Fixes resource leak in certificate check.

### CODE REVIEW

**Comment by konklone** [comment]
Ahhh! Thank you!

**Comment by konklone** [comment]
I've tested this and confirmed it addresses some causes of hanging, and deployed it to production. I really appreciate this @prefork! You've really lived up to your GitHub handle.

**Comment by prefork** [comment]
@konklone I'm glad I could lend a hand.  Thanks for setting this project up.

**Comment by konklone** [comment]
Aw - got another ENOMEM crash. :(

```
Checking domain: themeforest.net, themeforest.net
Error: spawn ENOMEM
    at errnoException (child_process.js:1001:11)
    at ChildProcess.spawn (child_process.js:948:11)
    at exports.spawn (child_process.js:736:9)
    at Object.exports.execFile (child_process.js:618:15)
    at exports.exec (child_process.js:589:18)
    at Object.Shaaa.certs (/home/shaaaaa/shaaaaa/current/shaaaaa.js:101:5)
    at Object.Shaaa.from (/home/shaaaaa/shaaaaa/current/shaaaaa.js:168:11)
    at /home/shaaaaa/shaaaaa/current/routes.js:22:13
    at Layer.handle [as handle_request] (/home/shaaaaa/shaaaaa/current/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/shaaaaa/shaaaaa/current/node_modules/express/lib/router/route.js:110:13)
```

**Comment by jonnybarnes** [comment]
A properly rough hack to fix this would be a cron job that restarts the process every 24hrs.

**Pull request merged**
